//[example_output
>example
Running 12 test cases...
test 1: 0, 0
test 1: 0, 1
test 1: 0, 2
test 1: 1, 0
test 1: 1, 1
test 1: 1, 2
test 2: 0 / 1.00002, 0
test 2: 0 / 1.08503, 1
test 2: 1 / 1.60135, 0
test 2: 1 / 1.89161, 1
example64.cpp:40: error: in "test_case_snippet_2": check random_sample < 1.7 has failed
Failure occurred in a following context:
    xr = 1; random_sample = 1.89161134; index = 1; 
test 2: 2 / 1.96796, 0
example64.cpp:40: error: in "test_case_snippet_2": check random_sample < 1.7 has failed
Failure occurred in a following context:
    xr = 2; random_sample = 1.96795571; index = 0; 
test 2: 2 / 1.18969, 1

*** 2 failures detected in test module "Master Test Suite"
//]