//[example_output
>example
Running 14 test cases...
test 1 3
test 1 15
test 1 3
test 1 1
test 1 5
test 1 9
test 1 8
test 2 1.00002
test 2 1.08503
test 2 1.60135
test 2 1.89161
example63.cpp:33: error: in "test_case_snippet_2": check random_sample < 1.7 has failed
Failure occurred in a following context:
    random_sample = 1.89161134; index = 3; 
test 2 1.96796
example63.cpp:33: error: in "test_case_snippet_2": check random_sample < 1.7 has failed
Failure occurred in a following context:
    random_sample = 1.96795571; index = 4; 
test 2 1.18969
test 2 1.51498

*** 2 failures detected in test module "Master Test Suite"
//]